# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qqXXXjvJq8EEJ_cJ9Toi5YcbzXzqRwn
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# 1. Create Sample Dataset

data = {
 "area": [1000, 1500, 2000, 2500, 3000, 1200, 1800, 2200, 2800, 3500],
 "bedrooms": [2, 3, 3, 4, 4, 2, 3, 3, 4, 5],
 "age": [10, 5, 8, 3, 2, 12, 7, 6, 4, 1],
 "price": [200000, 300000, 350000, 450000, 500000,
 220000, 330000, 370000, 480000, 600000]
}

df = pd.DataFrame(data)

X = df[["area", "bedrooms", "age"]]
y = df["price"]

# 2. Create Pipeline

pipeline = Pipeline([
 ("scaler", StandardScaler()),
 ("model", LinearRegression())
])

# 3. Train Model

pipeline.fit(X, y)

# 4. Save Pipeline

joblib.dump(pipeline, "pipeline.pkl")

print("Model trained and saved successfully.")